<?php

namespace App\Model\Formulir;

use Illuminate\Database\Eloquent\Model;

class PaketPekerjaanModel extends Model
{
    protected $table = 'tbl_paket_pekerjaan';
    public $incrementing = false;
    public $timestamps = false;

    protected $fillable = [
      'id'
      ,  'tahun'
      ,  'kdsatker'
      ,  'kdprogram'
      ,  'kdgiat'
      ,  'kdoutput'
      ,  'kdsoutput'
      ,  'kdkmpnen'
      ,  'kdskmpnen'
      ,  'kdpaket'
      ,  'kdls'
      ,  'nmpaket'
      ,  'vol'
      ,  'sat'
      ,  'kdlokasi'
      ,  'kdkabkota'
      ,  'pagu_51'
      ,  'pagu_52'
      ,  'pagu_53'
      ,  'pagu_rpm'
      ,  'pagu_sbsn'
      ,  'pagu_phln'
      ,  'pagu_total'
      ,  'real_51'
      ,  'real_52'
      ,  'real_53'
      ,  'real_rpm'
      ,  'real_sbsn'
      ,  'real_phln'
      ,  'real_total'
      ,  'progres_keuangan'
      ,  'progres_fisik'
      ,  'progres_keu_jan'
      ,  'progres_keu_feb'
      ,  'progres_keu_mar'
      ,  'progres_keu_apr'
      ,  'progres_keu_mei'
      ,  'progres_keu_jun'
      ,  'progres_keu_jul'
      ,  'progres_keu_agu'
      ,  'progres_keu_sep'
      ,  'progres_keu_okt'
      ,  'progres_keu_nov'
      ,  'progres_keu_des'
      ,  'progres_fisik_jan'
      ,  'progres_fisik_feb'
      ,  'progres_fisik_mar'
      ,  'progres_fisik_apr'
      ,  'progres_fisik_mei'
      ,  'progres_fisik_jun'
      ,  'progres_fisik_jul'
      ,  'progres_fisik_agu'
      ,  'progres_fisik_sep'
      ,  'progres_fisik_okt'
      ,  'progres_fisik_nov'
      ,  'progres_fisik_des'
      ,  'ren_keu_jan'
      ,  'ren_keu_feb'
      ,  'ren_keu_mar'
      ,  'ren_keu_apr'
      ,  'ren_keu_mei'
      ,  'ren_keu_jun'
      ,  'ren_keu_jul'
      ,  'ren_keu_agu'
      ,  'ren_keu_sep'
      ,  'ren_keu_okt'
      ,  'ren_keu_nov'
      ,  'ren_keu_des'
      ,  'ren_fis_jan'
      ,  'ren_fis_feb'
      ,  'ren_fis_mar'
      ,  'ren_fis_apr'
      ,  'ren_fis_mei'
      ,  'ren_fis_jun'
      ,  'ren_fis_jul'
      ,  'ren_fis_agu'
      ,  'ren_fis_sep'
      ,  'ren_fis_okt'
      ,  'ren_fis_nov'
      ,  'ren_fis_des'
      ,  'rkn_nama'
      ,  'rkn_npwp'
      ,  'nomor_kontrak'
      ,  'nilai_kontrak'
      ,  'tanggal_kontrak'
      ,  'waktu_pelaksanaan'
      ,  'created_at'
      ,  'updated_at'
      ,  'deleted_at'
      ,  'tgl_spmk'
      ,  'kdppk'
    ];

}
